# Version 0.1 [March.2023, TF]
name: CallPullRequest

on:
  # Trigger the workflow on pull request,
  pull_request:

  # allow for manual start of the test
  workflow_dispatch:

jobs:
  PR:
    uses: vistron-gmbh/Vistron.GitHub.Actions/.github/workflows/PullRequest.yml@main
    secrets: inherit
